---
# tasks file for openstack-presetup
- name: install openstack require package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - lvm2
    - "{{ (ansible_distribution == 'RedHat')|ternary('https://www.rdoproject.org/repos/rdo-release.rpm', centos_rdo_rpm) }}"

- name: disable openstack unuse services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - NetworkManager
    - postfix

- block:
  - name: setup environment
    copy:
      src: environment
      dest: /etc/environment
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_environment_setting

  always:
  - name: openstack presetup backup settings
    include: backup.yml
    with_flattened:
      - "{{ is_environment_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install openstack
  package:
    name: openstack-packstack
    state: present
